scrape_configs:
  - job_name: 'h2-users-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:8080']
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']